README.md

Adds a section to the main `README`.
Provide information about a local deployment.
--
Closes #9

docs: add guide for a local deployment

---

docs/hands-on.md

Links to a document provided in the connector repo.
Help with understanding this project
In the long term, this "hands on" section should provide detailed information about how to build, use and extend data space components as described [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/2061#issuecomment-1271613575). 

docs(hands on): add link to build/run a connector

---

.gitmodules
docs/_sidebar.md

Adds https://github.com/eclipse-dataspaceconnector/GradlePlugins as submodule and links it in menu bar.
Include new EDC repo in GitHub pages.
--
Closes #8

chore: add GradlePlugins repository as submodule

---

.gitmodules
docs/_sidebar.md

Adds https://github.com/eclipse-dataspaceconnector/TrustFrameworkAdoption as submodule and links it in menu bar.
Include new EDC repo in GitHub pages.
--
Closes #16

chore(module): add Trust Framework Adoption repo

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/first-interaction.yml
.github/workflows/scan-pull-request.yml
.gitmodules
README.md
docs/404.md
docs/README.md
docs/_coverpage.md
docs/_navbar.md
docs/hands-on.md
docs/index.html
docs/package.json

Replace 
- all the `eclipse-dataspaceconnector` occurrencies with `eclipse-dataspacecomponents`
- all the `technology.dataspaceconnector` occurrencies with `technolody.edc`
rebranding
- aligned pr title length with other repositories
Closes #22

docs: Replace dataspaceconnector occurrencies with dataspacecomponents

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/first-interaction.yml
.gitmodules
README.md
docs/404.md
docs/README.md
docs/_coverpage.md
docs/hands-on.md
docs/index.html
docs/package.json

Adapt to the definitive `eclipse-edc` organization.
Renamed occurrencies of `DataSpaceConnector` to `Connector` as well
rebranding

docs: Further url updates

---

.github/workflows/discord-webhook.yml

Replaces `inputs` with `with`.
Resolve error 
> The workflow is not valid. .github/workflows/discord-webhook.yml (Line: 13, Col: 5): Unexpected value 'inputs'

fix: replace unexpected value in discord webhook workflow

---

.gitmodules
README.md
docs/README.md
docs/_sidebar.md

Adds .github repo as submodule. Replaces references to Connector documentation with links to .github.
Follow changes in eclipse-edc/Connector.
Relates eclipse-edc/Connector#3033

feat: add .github repo as submodule

---

docs/developer/developer-handbook.md

Adds TOC for the developer documentation
Preparatory work for a more streamlined documentation experience

docs: add TOC for the developer handbook

---

docs/developer/developer-handbook.md

this PR adds the following chapters to the handbook:
- Introduction
- Building a distribution
- Core Concepts
- Control Plane / API objects / Assets
documentation
There is no real reason as to why I added exactly those chapters in this PR other than it seemed to be a digestible amount of text. 
More chapters should be done in subsequent PRs.

docs: add developer handbook chapters

---

docs/_sidebar.md
docs/index.html
docs/style/sidebar.css

Adds `Developer` and `Decision Records` links for every component in the sidebar.
e.g.
Improve browsability.
- converted the _sidebar.md file to pure markdown, it seems to work fine.
- added the [docsify-sidebar-collapse](https://www.npmjs.com/package/docsify-sidebar-collapse) plugin to have a more readable menu
Closes #82 

feat: add developer and decision records links on sidebar

---

developer/decision-records/2023-09-12-publishing_from_github/README.md

Adds a decision record about publishing to OSSRH/MavenCentral directly from GH Actions.
tracking decisions
- subsequent implementation PRs should focus on the snapshot builds first.

docs: decision record about publishing to OSSRH

---

.github/workflows/update-submodules.yml

Removes assignee, adds a Git pull, and adds commit options.
The assignee was automatically set to me, not necessary. Same goes for the commit author.
Adds a Git pull to ensure that the workflows are up-to-date: https://github.com/eclipse-edc/docs/actions/runs/6402422400/job/17379014220

chore: improve action to update submodules

---

.github/workflows/update-submodules.yml

Adds the EDC bot (configuration from https://github.com/eclipse-edc/.github/blob/main/.github/actions/bump-version/action.yml).
The ECA check fails for GH Actions bot:
See [here](https://github.com/stefanzweifel/git-auto-commit-action#usage) for the action's guide.

chore: configure EDC bot

---

developer/handbook.md

Adds a chapter about Transfer Processes to the handbook.
documentation

docs: add chapter about transferprocesses

---

contributing/adoption.md
contributing/pr_etiquette.md

* updated the path to adoption request temlpate.
* made link to scan-pull-request.yml external since docsify can not render the local .yml file.
Closes #130

fix: fix dead links related to .github resources

---

developer/handbook.md
docs/_sidebar.md
docs/hands-on.md

Add links to see the github-pages hosted documentation about modules and openapi.
In the menu they will be more visible than to be in the hands-on page, and this way every component will have their own generated documentation
Preview:
documentation

docs: add links for connector autodoc and openapi ui

---

developer/handbook.md

updated links to documentation of Samples checked out by `git submodule`.
in order to fix 404.
Closes #135

fix: fix dead links to documentation of Samples

---

developer/decision-records/2024-04-19-tech-repo-split/README.md
developer/decision-records/README.md

Adds a decision record about separating the release process of our technology repos
Make decisions transparent

docs: add decision record about repo separation

---

.gitmodules
docs/_sidebar.md

Removed references about the archived project [RegistrationService](https://github.com/eclipse-edc/RegistrationService)
cleanup
- added `shallow = true` on the documentation self submodule, to avoid recursive fetch.
Closes #155 

refactor: remove RegistrationService

---

developer/decision-records/2024-07-17-bootstrap-sql-database/README.md
developer/decision-records/README.md

Adds a decision record about the automatic schema bootstrapping facility.
Ease-of-use, convenience
Contributes to https://github.com/eclipse-edc/Connector/issues/4356

docs: decision record about SQL schema bootstrapper

---

developer/decision-records/2024-08-13-technology-repos-release/README.md
developer/decision-records/README.md

Adds decision record about the new release process for `Technology` repositories
documentation

docs: add DR for technology repositories release

---

developer/wip/for-contributors/contributor-handbook.md

adds links to sub-documents from the dataplane signaling chapter in the main contributor doc

chore(docs): add links to data plane signaling
