developer/handbook.md
Adds a chapter about contract negotiation/agreement and also the catalog.
documentation
=> docs: add chapter about contract negotiation/agreement

docs/README.md
Adds Eona-X to the list of correlating projects
=> docs: add Eona-X to list of correlating projects

docs/README.md
_Briefly describe WHAT your pr changes, which features it adds/modifies._
Closes #125 
=> fix: broken known friends link

developer/decision-records/2024-05-20-api-versioning-2/README.md
Adds an addendum to the existing API versioning decision record(s) we already have. It outlines in more detail:
- how APIs are versioned
- how to obtain that information
- the api groups (or "contexts")
Transparency, traceable decisions
=> docs: add addendum re API versioning

docs/_sidebar.md
_Briefly describe WHAT your pr changes, which features it adds/modifies._
Closes #153 
=> fix: resolve 404

docs/index.html
Fixes the anchor jump which is not currently working
=> chore: fix anchor scroll

.github/workflows/publish.yml
Add workflow to publish to gh-pages branch
fix publish process
Closes #169 
=> build: publish gh pages

developer/wip/for-contributors/contributor-handbook.md
Adds the outline of the contributor handbook plus the "getting started" chapter
- individual headlines are "working titles", we can always change them down the road.
=> docs: add contributor handbooke (outline + getting-started)

developer/wip/for-contributors/contributor-handbook.md
Adds a section about assets and policies
documentation
=> docs: add section about assets and policies

developer/wip/for-contributors/contributor-handbook.md
section about contracts and the catalog.
=> docs: add section about contracts and catalogs

developer/wip/for-contributors/contributor-handbook.md
Adds chapter about state machines etc.
=> docs: add chapter about state machines

developer/wip/for-contributors/contributor-handbook.md
add section about query spec.
The translation strategy from `QuerySpec`   has not been drafted in this PR, but it has  has been moved into the store section.
=> docs: add section about query spec

developer/wip/for-contributors/contributor-handbook.md
Adds a chapter about transformers
=> docs: add chapter about transformers

developer/wip/for-contributors/contributor-handbook.md
Adds a chapter about creating and validating tokens.
=> docs: add chapter about tokens

developer/wip/for-contributors/contributor-handbook.md
adds a chapter about dependency injection and the extension model
=> docs: add chapter about the extension model and DI

developer/wip/for-contributors/contributor-handbook.md
section about JSON-LD serialization
improve documentation
=> docs: JSON-LD serialization

developer/wip/for-contributors/contributor-handbook.md
Adds a chapter about service layers
=> docs: add chapter about service layers

developer/wip/for-contributors/contributor-handbook.md, developer/wip/for-contributors/postgres-persistence.md
=> docs: add chapter about sql persistence

developer/decision-records/2024-08-16-new-template-repo/README.md
adds a decision record about the template repo
=> docs: add decision record about template repo

developer/wip/for-contributors/contributor-handbook.md, developer/wip/for-contributors/control-plane/protocol-extensions.md
section about protocols extensions
improve documentation
=> docs: section about protocols extensions

developer/decision-records/2024-08-26-new-release-process/README.md, developer/decision-records/README.md
Adds a DR for the new release process
documentation
=> docs: add DR for the new release process

developer/wip/for-adopters/edc-testing.md
Add documentation on the JUnit runtime
=> docs: Add testing documentation

developer/wip/for-contributors/contributor-handbook.md
adds a chapter about the gradle build and the release process
=> docs: add chapter about gradle build
